// context/ProductsContext.jsx
import { createContext, useContext, useState } from "react";

const ProductsContext = createContext();

export function ProductsProvider({ children }) {
  const [products] = useState([
      { id: 1, img: "/imagesProducts/akıllıEv.webp", title: "Akıllı Ev PCB", price: "Akıllı ev cihazları, kablosuz iletişim, otomasyon, algılama ve kontrol sağlamak için çok çeşitli bileşenleri entegre eden gelişmiş PCB montajlarına dayanır.Akıllı ev PCB düzenekleri, modern yaşam ortamlarında konforu, güvenliği, enerji verimliliğini ve bağlantıyı artıran çok çeşitli akıllı cihazlara güç sağlar." },
      { id: 2, img: "/imagesProducts/elevatorControl.jpg", title: "Elevator Control PCB", price: "Baskılı Devre Kartları (PCB'ler), modern asansör kontrol sistemlerinin temel omurgasını oluşturur ve güvenlik, hareket, iletişim ve kullanıcı arayüzlerini yönetmek için kritik bir platform sağlar. PCB'ler, asansörün sorunsuz, güvenilir ve emniyetli bir şekilde çalışmasını sağlamak için gereken karmaşık sensör, motor sürücüsü, mikrodenetleyici ve iletişim modülü ağını birbirine bağlar ve koordine eder." },
      { id: 3, img: "/imagesProducts/facialRecognition.jpg", title: "Facial Recognition PCB", price: "Baskılı Devre Kartları (PCB'ler), yüz tanıma sistemlerinin temel omurgasını oluşturarak, birden fazla yüksek performanslı bileşenin kompakt ve güvenilir bir platformda entegre edilmesini sağlar. Görüntü sensörlerini, mikroişlemcileri, bellek modüllerini ve iletişim arayüzlerini birbirine bağlayan elektrik yollarını sağlayarak, kesintisiz veri yakalama, işleme ve iletimini garantiler." },
      { id: 4, img: "/imagesProducts/powerControl.jpg", title: "Power Control PCB", price: "Güç Kontrol PCB Montajı, birçok elektronik cihazın kalbinde yer alır ve sorunsuz ve verimli bir şekilde çalışmasını sağlar. Elektronik sistemlerdeki elektrik gücünü yöneten, düzenleyen ve dağıtan baskılı devre kartlarının tasarlanıp monte edilmesiyle ilgili özel bir süreci ifade eder. Bu PCB'ler, endüstriyel makineler, elektrikli araçlar, güç kaynakları, yenilenebilir enerji sistemleri ve motor sürücüleri gibi yüksek akım, yüksek voltaj veya güç dönüşümü içeren uygulamalarda kritik öneme sahiptir." },
      { id: 5, img: "/imagesProducts/tüketiciE.jpg", title: "Tüketici Elektroniği PCB", price: "Tüketici elektroniği PCB'leri, akıllı telefonlar, akıllı saatler, dizüstü bilgisayarlar, TV'ler, oyun konsolları ve giyilebilir teknoloji gibi cihazlarda sorunsuz işlevsellik sağlayarak kompakt, verimli ve güçlü olmalıdır."},
      { id: 6, img: "/imagesProducts/yeniE.jpg", title: "Yeni Enerji Ve Otomotiv PCB", price: "Elektrikli araçlar (EV'ler), hibrit elektrikli araçlar (HEV'ler) ve yakıt hücreli araçlar dahil olmak üzere Yeni Enerji Araçları (NEV'ler), gelişmiş elektronik sistemlerini desteklemek için büyük ölçüde özel PCB'lere (Baskı Devre Kartları) güvenmektedir. Geleneksel araçların aksine, NEV'ler zorlu çalışma koşullarında güvenli ve verimli performans sağlamak için yüksek güvenilirlikli, yüksek güçlü ve termal olarak optimize edilmiş PCB'lere ihtiyaç duyar." },
            { id: 1, img: "/imagesProducts/akıllıEv.webp", title: "Akıllı Ev PCB", price: "Akıllı ev cihazları, kablosuz iletişim, otomasyon, algılama ve kontrol sağlamak için çok çeşitli bileşenleri entegre eden gelişmiş PCB montajlarına dayanır.Akıllı ev PCB düzenekleri, modern yaşam ortamlarında konforu, güvenliği, enerji verimliliğini ve bağlantıyı artıran çok çeşitli akıllı cihazlara güç sağlar." },
      { id: 2, img: "/imagesProducts/elevatorControl.jpg", title: "Elevator Control PCB", price: "Baskılı Devre Kartları (PCB'ler), modern asansör kontrol sistemlerinin temel omurgasını oluşturur ve güvenlik, hareket, iletişim ve kullanıcı arayüzlerini yönetmek için kritik bir platform sağlar. PCB'ler, asansörün sorunsuz, güvenilir ve emniyetli bir şekilde çalışmasını sağlamak için gereken karmaşık sensör, motor sürücüsü, mikrodenetleyici ve iletişim modülü ağını birbirine bağlar ve koordine eder." },
      { id: 3, img: "/imagesProducts/facialRecognition.jpg", title: "Facial Recognition PCB", price: "Baskılı Devre Kartları (PCB'ler), yüz tanıma sistemlerinin temel omurgasını oluşturarak, birden fazla yüksek performanslı bileşenin kompakt ve güvenilir bir platformda entegre edilmesini sağlar. Görüntü sensörlerini, mikroişlemcileri, bellek modüllerini ve iletişim arayüzlerini birbirine bağlayan elektrik yollarını sağlayarak, kesintisiz veri yakalama, işleme ve iletimini garantiler." },
      { id: 4, img: "/imagesProducts/powerControl.jpg", title: "Power Control PCB", price: "Güç Kontrol PCB Montajı, birçok elektronik cihazın kalbinde yer alır ve sorunsuz ve verimli bir şekilde çalışmasını sağlar. Elektronik sistemlerdeki elektrik gücünü yöneten, düzenleyen ve dağıtan baskılı devre kartlarının tasarlanıp monte edilmesiyle ilgili özel bir süreci ifade eder. Bu PCB'ler, endüstriyel makineler, elektrikli araçlar, güç kaynakları, yenilenebilir enerji sistemleri ve motor sürücüleri gibi yüksek akım, yüksek voltaj veya güç dönüşümü içeren uygulamalarda kritik öneme sahiptir." },
      { id: 5, img: "/imagesProducts/tüketiciE.jpg", title: "Tüketici Elektroniği PCB", price: "Tüketici elektroniği PCB'leri, akıllı telefonlar, akıllı saatler, dizüstü bilgisayarlar, TV'ler, oyun konsolları ve giyilebilir teknoloji gibi cihazlarda sorunsuz işlevsellik sağlayarak kompakt, verimli ve güçlü olmalıdır."},
      { id: 6, img: "/imagesProducts/yeniE.jpg", title: "Yeni Enerji Ve Otomotiv PCB", price: "Elektrikli araçlar (EV'ler), hibrit elektrikli araçlar (HEV'ler) ve yakıt hücreli araçlar dahil olmak üzere Yeni Enerji Araçları (NEV'ler), gelişmiş elektronik sistemlerini desteklemek için büyük ölçüde özel PCB'lere (Baskı Devre Kartları) güvenmektedir. Geleneksel araçların aksine, NEV'ler zorlu çalışma koşullarında güvenli ve verimli performans sağlamak için yüksek güvenilirlikli, yüksek güçlü ve termal olarak optimize edilmiş PCB'lere ihtiyaç duyar." },
            { id: 1, img: "/imagesProducts/akıllıEv.webp", title: "Akıllı Ev PCB", price: "Akıllı ev cihazları, kablosuz iletişim, otomasyon, algılama ve kontrol sağlamak için çok çeşitli bileşenleri entegre eden gelişmiş PCB montajlarına dayanır.Akıllı ev PCB düzenekleri, modern yaşam ortamlarında konforu, güvenliği, enerji verimliliğini ve bağlantıyı artıran çok çeşitli akıllı cihazlara güç sağlar." },
      { id: 2, img: "/imagesProducts/elevatorControl.jpg", title: "Elevator Control PCB", price: "Baskılı Devre Kartları (PCB'ler), modern asansör kontrol sistemlerinin temel omurgasını oluşturur ve güvenlik, hareket, iletişim ve kullanıcı arayüzlerini yönetmek için kritik bir platform sağlar. PCB'ler, asansörün sorunsuz, güvenilir ve emniyetli bir şekilde çalışmasını sağlamak için gereken karmaşık sensör, motor sürücüsü, mikrodenetleyici ve iletişim modülü ağını birbirine bağlar ve koordine eder." },
      { id: 3, img: "/imagesProducts/facialRecognition.jpg", title: "Facial Recognition PCB", price: "Baskılı Devre Kartları (PCB'ler), yüz tanıma sistemlerinin temel omurgasını oluşturarak, birden fazla yüksek performanslı bileşenin kompakt ve güvenilir bir platformda entegre edilmesini sağlar. Görüntü sensörlerini, mikroişlemcileri, bellek modüllerini ve iletişim arayüzlerini birbirine bağlayan elektrik yollarını sağlayarak, kesintisiz veri yakalama, işleme ve iletimini garantiler." },
      { id: 4, img: "/imagesProducts/powerControl.jpg", title: "Power Control PCB", price: "Güç Kontrol PCB Montajı, birçok elektronik cihazın kalbinde yer alır ve sorunsuz ve verimli bir şekilde çalışmasını sağlar. Elektronik sistemlerdeki elektrik gücünü yöneten, düzenleyen ve dağıtan baskılı devre kartlarının tasarlanıp monte edilmesiyle ilgili özel bir süreci ifade eder. Bu PCB'ler, endüstriyel makineler, elektrikli araçlar, güç kaynakları, yenilenebilir enerji sistemleri ve motor sürücüleri gibi yüksek akım, yüksek voltaj veya güç dönüşümü içeren uygulamalarda kritik öneme sahiptir." },
      { id: 5, img: "/imagesProducts/tüketiciE.jpg", title: "Tüketici Elektroniği PCB Tüketici Elektroniği PCB", price: "Tüketici elektroniği PCB'leri, akıllı telefonlar, akıllı saatler, dizüstü bilgisayarlar, TV'ler, oyun konsolları ve giyilebilir teknoloji gibi cihazlarda sorunsuz işlevsellik sağlayarak kompakt, verimli ve güçlü olmalıdır."},
      { id: 6, img: "/imagesProducts/yeniE.jpg", title: "Yeni Enerji Ve Otomotiv PCB", price: "Elektrikli araçlar (EV'ler), hibrit elektrikli araçlar (HEV'ler) ve yakıt hücreli araçlar dahil olmak üzere Yeni Enerji Araçları (NEV'ler), gelişmiş elektronik sistemlerini desteklemek için büyük ölçüde özel PCB'lere (Baskı Devre Kartları) güvenmektedir. Geleneksel araçların aksine, NEV'ler zorlu çalışma koşullarında güvenli ve verimli performans sağlamak için yüksek güvenilirlikli, yüksek güçlü ve termal olarak optimize edilmiş PCB'lere ihtiyaç duyar." },
            { id: 1, img: "/imagesProducts/akıllıEv.webp", title: "Akıllı Ev PCB", price: "Akıllı ev cihazları, kablosuz iletişim, otomasyon, algılama ve kontrol sağlamak için çok çeşitli bileşenleri entegre eden gelişmiş PCB montajlarına dayanır.Akıllı ev PCB düzenekleri, modern yaşam ortamlarında konforu, güvenliği, enerji verimliliğini ve bağlantıyı artıran çok çeşitli akıllı cihazlara güç sağlar." },
      { id: 2, img: "/imagesProducts/elevatorControl.jpg", title: "Elevator Control PCB", price: "Baskılı Devre Kartları (PCB'ler), modern asansör kontrol sistemlerinin temel omurgasını oluşturur ve güvenlik, hareket, iletişim ve kullanıcı arayüzlerini yönetmek için kritik bir platform sağlar. PCB'ler, asansörün sorunsuz, güvenilir ve emniyetli bir şekilde çalışmasını sağlamak için gereken karmaşık sensör, motor sürücüsü, mikrodenetleyici ve iletişim modülü ağını birbirine bağlar ve koordine eder." },
      { id: 3, img: "/imagesProducts/facialRecognition.jpg", title: "Facial Recognition PCB", price: "Baskılı Devre Kartları (PCB'ler), yüz tanıma sistemlerinin temel omurgasını oluşturarak, birden fazla yüksek performanslı bileşenin kompakt ve güvenilir bir platformda entegre edilmesini sağlar. Görüntü sensörlerini, mikroişlemcileri, bellek modüllerini ve iletişim arayüzlerini birbirine bağlayan elektrik yollarını sağlayarak, kesintisiz veri yakalama, işleme ve iletimini garantiler." },
      { id: 4, img: "/imagesProducts/powerControl.jpg", title: "Power Control PCB", price: "Güç Kontrol PCB Montajı, birçok elektronik cihazın kalbinde yer alır ve sorunsuz ve verimli bir şekilde çalışmasını sağlar. Elektronik sistemlerdeki elektrik gücünü yöneten, düzenleyen ve dağıtan baskılı devre kartlarının tasarlanıp monte edilmesiyle ilgili özel bir süreci ifade eder. Bu PCB'ler, endüstriyel makineler, elektrikli araçlar, güç kaynakları, yenilenebilir enerji sistemleri ve motor sürücüleri gibi yüksek akım, yüksek voltaj veya güç dönüşümü içeren uygulamalarda kritik öneme sahiptir." },
      { id: 5, img: "/imagesProducts/tüketiciE.jpg", title: "Tüketici Elektroniği PCB", price: "Tüketici elektroniği PCB'leri, akıllı telefonlar, akıllı saatler, dizüstü bilgisayarlar, TV'ler, oyun konsolları ve giyilebilir teknoloji gibi cihazlarda sorunsuz işlevsellik sağlayarak kompakt, verimli ve güçlü olmalıdır."},
      { id: 6, img: "/imagesProducts/yeniE.jpg", title: "Yeni Enerji Ve Otomotiv PCB", price: "Elektrikli araçlar (EV'ler), hibrit elektrikli araçlar (HEV'ler) ve yakıt hücreli araçlar dahil olmak üzere Yeni Enerji Araçları (NEV'ler), gelişmiş elektronik sistemlerini desteklemek için büyük ölçüde özel PCB'lere (Baskı Devre Kartları) güvenmektedir. Geleneksel araçların aksine, NEV'ler zorlu çalışma koşullarında güvenli ve verimli performans sağlamak için yüksek güvenilirlikli, yüksek güçlü ve termal olarak optimize edilmiş PCB'lere ihtiyaç duyar." }
    ]);


  return (
    <ProductsContext.Provider value={{ products }}>
      {children}
    </ProductsContext.Provider>
  );
}

export function useProducts() {
  return useContext(ProductsContext);
}
